
addons:
  apt:
    packages:
    - aria2
#before_install:
branches:
  only:
  - develop
  - master

dist: trusty
env:
  global:
  - IMAGE_ARG_APT_MIRROR=archive.ubuntu.com
  - IMAGE_ARG_FILESERVER=
  matrix:
  - IMAGE_ARG_DOCKERCE_VERSION=18.03.1~ce~3-0 IMAGE_ARG_DOCKERCOMPOSE_VERSION=1.21.2 IMAGE_ARG_DOCKERMACHINE_VERSION=0.14.0
  - IMAGE_ARG_DOCKERCE_VERSION=18.06.1~ce~3-0 IMAGE_ARG_DOCKERCOMPOSE_VERSION=1.21.2 IMAGE_ARG_DOCKERMACHINE_VERSION=0.14.0

group: edge
#install: true

#before_script:
script:
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- bash build.sh
- kill %1
#after_script:

services:
- docker
sudo: required
