
FROM cirepo/nix:2.2.1-bionic


COPY --chown=ubuntu:ubuntu docker /home/ubuntu/data


# Process image layers
RUN cd /home/${USER:-ubuntu} \
  && ./data/dump.sh
#  && sudo chown -R ${USER:-ubuntu}:$(id -gn) /data/root/home/${USER:-ubuntu}
